WIP: #2 Use redis-py instead of aioredis to support redis-py 4+
enchant97/quart-redis pull request #3
Opened 2023-03-17 14:47 UTC by rmartin-federated

Fix for #2 
Shutdown method not yet functional

2023-03-17 15:25 UTC, enchant97 requested changes
Thanks for current work I haven't had time to migrate it to redis 4, however I think there needs to be some changes before it can be merged.

Also the pip requirement `aioredis ~= 2.0` in setup.cfg will need changing to something like: `redis >= 4.2, < 5`.

2023-03-17 15:25 UTC, enchant97 commented on quart_redis/__init__.py
> +from redis import from_url
Looking at the docs should this not be:

```python
from redis.asyncio import Redis, from_url
```

2023-03-17 15:25 UTC, enchant97 commented on quart_redis/__init__.py
> +    print('Our Fork')
I don't think this should be here

2023-03-17 15:25 UTC, enchant97 commented on quart_redis/__init__.py
> +            RedisHandler._connection.close()
The docs say it's an awaitable: [example](https://redis-py.readthedocs.io/en/stable/examples/asyncio_examples.html#Connecting-and-Disconnecting)

2023-03-17 15:37 UTC, ltsar-federated commented
So we are encountering an issue where the "Redis" object returned from `get_redis` is having it's namespace clobbered and refusing to be `await`ed. We are going to use explicit typing for the return types from `get_redis` like `-> aioredis.Redis`

2023-03-17 15:42 UTC, ltsar-federated commented
Actually it seems like PyCharm is just wrong, code seems to work fine with the awaits. Pushing new commit shortly. Thanks for the head start!

2023-03-17 15:47 UTC, ltsar-federated commented on quart_redis/__init__.py
> +from redis import from_url
Got it in latest commit
@rmartin-federated

2023-03-17 15:48 UTC, ltsar-federated commented
Newest push should be good. Thanks for the speedy review! @rmartin-federated

2023-03-17 16:44 UTC, enchant97 requested changes

2023-03-17 16:44 UTC, enchant97 commented on quart_redis/__init__.py
> +        print(f'Type Returned: {type(cls._connection)}')
Remove this, otherwise it will pollute people's stdout.

2023-03-21 17:08 UTC, enchant97 approved these changes

2023-03-21 17:11 UTC, merged